### ISSUE TITLE
Unable to complete install and setup of DermoDex 

### ISSUE THREAD

**Issue by 13gemini** [duracell80/DermoDeX#1]
duracell80

I am using Linux Mint Cinnamon 21.1 and downloaded the duracell80/DermoDeX. After running install.sh, I have some functionality, but am unable to use the color overides. I was initially getting matplotlib hash errors but corrected that with a download from [https://files.pythonhosted.org/packages ... bf7fd2f03b](https://files.pythonhosted.org/packages/44/15/4225ce5758885913338c8bf2bf2cad8bd00691fdcfea85147450a4eb495d/matplotlib-3.6.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl#sha256=59400cc9451094b7f08cc3f321972e6e1db4cd37a978d4e8a12824bf7fd2f03b):

That cleared that up. However, I received a ton of no such file or directory.

I have included the terminal install below, and you will note, I have attempted to run the install.sh several times with the same outcome.

Hope you can help

gemini13

Before running the install note the changes documented such as needing to backup your /usr/share/sounds directory.
[Q] Do you wish to continue (y/n)? y

- Installing Deps from APT and PIP
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
xz-utils is already the newest version (5.2.5-2ubuntu1).
imagemagick is already the newest version (8:6.9.11.60+dfsg-1.3build2).
inkscape is already the newest version (1.1.2-3ubuntu1).
libsass1 is already the newest version (3.6.5-1ubuntu1).
rofi is already the newest version (1.7.1-0.1).
sassc is already the newest version (3.6.1+20201027-2).
scrot is already the newest version (1.7-1).
sox is already the newest version (14.4.2+git20190427-2).
xdotool is already the newest version (1:3.20160805.1-4).
ffmpeg is already the newest version (7:4.4.2-0ubuntu0.22.04.1).
python3-pip is already the newest version (22.0.2+dfsg-1ubuntu0.1).
0 upgraded, 0 newly installed, 0 to remove and 3 not upgraded.
Requirement already satisfied: easydev in /usr/local/lib/python3.10/dist-packages (0.12.0)
Requirement already satisfied: colorlog in /usr/local/lib/python3.10/dist-packages (from easydev) (6.7.0)
Requirement already satisfied: pexpect in /usr/lib/python3/dist-packages (from easydev) (4.8.0)
Requirement already satisfied: colorama in /usr/lib/python3/dist-packages (from easydev) (0.4.4)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
Requirement already satisfied: colormap in /usr/local/lib/python3.10/dist-packages (1.0.4)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (1.5.3)
Requirement already satisfied: python-dateutil>=2.8.1 in /usr/local/lib/python3.10/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/lib/python3/dist-packages (from pandas) (2022.1)
Requirement already satisfied: numpy>=1.21.0 in /usr/lib/python3/dist-packages (from pandas) (1.21.5)
Requirement already satisfied: six>=1.5 in /usr/lib/python3/dist-packages (from python-dateutil>=2.8.1->pandas) (1.16.0)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
Requirement already satisfied: numpy in /usr/lib/python3/dist-packages (1.21.5)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
Requirement already satisfied: colorgram.py in /usr/local/lib/python3.10/dist-packages (1.2.0)
Requirement already satisfied: pillow>=3.3.1 in /usr/lib/python3/dist-packages (from colorgram.py) (9.0.1)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
Requirement already satisfied: extcolors in /usr/local/lib/python3.10/dist-packages (1.0.0)
Requirement already satisfied: Pillow>=8.0.0 in /usr/lib/python3/dist-packages (from extcolors) (9.0.1)
Requirement already satisfied: convcolors>=1.0.0 in /usr/local/lib/python3.10/dist-packages (from extcolors) (2.2.0)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
Requirement already satisfied: matplotlib in /usr/local/lib/python3.10/dist-packages (3.6.3)
Requirement already satisfied: numpy>=1.19 in /usr/lib/python3/dist-packages (from matplotlib) (1.21.5)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.10/dist-packages (from matplotlib) (0.11.0)
Requirement already satisfied: packaging>=20.0 in /usr/lib/python3/dist-packages (from matplotlib) (21.3)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib) (4.38.0)
Requirement already satisfied: pyparsing>=2.2.1 in /usr/lib/python3/dist-packages (from matplotlib) (2.4.7)
Requirement already satisfied: pillow>=6.2.0 in /usr/lib/python3/dist-packages (from matplotlib) (9.0.1)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib) (1.4.4)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib) (1.0.7)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.10/dist-packages (from matplotlib) (2.8.2)
Requirement already satisfied: six>=1.5 in /usr/lib/python3/dist-packages (from python-dateutil>=2.7->matplotlib) (1.16.0)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
Requirement already satisfied: configparser in /usr/local/lib/python3.10/dist-packages (5.3.0)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
Requirement already satisfied: xdisplayinfo in /usr/local/lib/python3.10/dist-packages (2.0.1)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
- Backing Up Current Cinnamon Configuration
sed: can't read /home/linuxcruizer/Downloads/scripts/cinnamon_dd.txt: No such file or directory
Installing Base Theme - Fluent
/home/linuxcruizer/Downloads/DermoDeX-main/install.sh: line 77: /home/linuxcruizer/Downloads/install-theme-base.sh: No such file or directory
Creating DermoDex Symlink in Pictures
ln: failed to create symbolic link '/root/Pictures/DermoDeX': No such file or directory
/home/linuxcruizer/Downloads/DermoDeX-main/install.sh: line 93: /root/.cinnamon/backgrounds/user-folders.lst: No such file or directory
1) none 5) petra 9) retro 13) sonya 17) tina 21) uma
2) maya 6) qiana 10) rosa 14) sylvia 18) tricia 22) una
3) nadia 7) rafaela 11) sarah 15) tara 19) ulyana 23) vanessa
4) olivia 8) rebecca 12) serena 16) tessa 20) ulyssa 24) vera
Choose a previous wallpaper set to install: 2
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
mint-backgrounds-maya is already the newest version (1.5).
0 upgraded, 0 newly installed, 0 to remove and 3 not upgraded.
cp: cannot stat '/home/linuxcruizer/Downloads/src/cinnamon/cinnamon-ext.css': No such file or directory
cp: cannot stat '/home/linuxcruizer/Downloads/src/headerbar.css': No such file or directory
cp: cannot stat '/home/linuxcruizer/Downloads/src/headerbar.css': No such file or directory
cp: cannot stat '/home/linuxcruizer/Downloads/src/sidebar.css': No such file or directory
cp: cannot stat '/home/linuxcruizer/Downloads/src/sidebar.css': No such file or directory
cp: cannot stat '/root/.config/gtk-3.0/gtk.css': No such file or directory
cp: cannot stat '/root/.cinnamon/configs/[menu@cinnamon.org](mailto:menu@cinnamon.org)/0.json': No such file or directory
cp: cannot stat './scripts/config_menu.json': No such file or directory
cp: cannot stat '/root/.cinnamon/configs/[workspace-switcher@cinnamon.org](mailto:workspace-switcher@cinnamon.org)/27.json': No such file or directory
cp: cannot stat '/home/linuxcruizer/Downloads/scripts/config_workspace.json': No such file or directory
cp: cannot stat '/home/linuxcruizer/Downloads/scripts/remix_sounds.sh': No such file or directory
cp: cannot stat '/home/linuxcruizer/Downloads/scripts/remix_themes.sh': No such file or directory
cp: cannot stat '/home/linuxcruizer/Downloads/scripts/remix_icons.sh': No such file or directory
cp: cannot stat '/home/linuxcruizer/Downloads/scripts/remix_color.py': No such file or directory
cp: cannot stat '/home/linuxcruizer/Downloads/scripts/remix_wallpapers.sh': No such file or directory
cp: cannot stat '/home/linuxcruizer/Downloads/scripts/sounds_waveform.sh': No such file or directory
cp: cannot stat '/home/linuxcruizer/Downloads/scripts/display_resolution.sh': No such file or directory
cp: cannot stat '/home/linuxcruizer/Downloads/scripts/cinnamon_reload': No such file or directory
cp: cannot stat '/home/linuxcruizer/Downloads/scripts/bin/dd_sleep.sh': No such file or directory
cp: cannot stat '/home/linuxcruizer/Downloads/scripts/bin/dd_wake.sh': No such file or directory
cp: cannot stat '/home/linuxcruizer/Downloads/scripts/bin/dd_hold.sh': No such file or directory
cp: cannot stat '/home/linuxcruizer/Downloads/scripts/bin/dd_release.sh': No such file or directory
cp: cannot stat '/home/linuxcruizer/Downloads/scripts/bin/dd_rescue.sh': No such file or directory
cp: cannot stat '/home/linuxcruizer/Downloads/scripts/bin/dd_reload.sh': No such file or directory
cp: cannot stat '/home/linuxcruizer/Downloads/scripts/bin/dd_refresh.sh': No such file or directory
cp: cannot stat '/home/linuxcruizer/Downloads/scripts/bin/dd_swatch.sh': No such file or directory
cp: cannot stat '/home/linuxcruizer/Downloads/scripts/bin/dex-notify.sh': No such file or directory
cp: cannot stat '/home/linuxcruizer/Downloads/scripts/bin/dex-action.sh': No such file or directory
cp: cannot stat '/home/linuxcruizer/Downloads/scripts/bin/.mpris.so': No such file or directory
cp: cannot stat '/home/linuxcruizer/Downloads/scripts/rofi/dd_power.sh': No such file or directory
cp: cannot stat '/home/linuxcruizer/Downloads/scripts/rofi/dd_radio.sh': No such file or directory
cp: cannot stat '/home/linuxcruizer/Downloads/scripts/rofi/dd_bluetooth.sh': No such file or directory
cp: cannot stat '/home/linuxcruizer/Downloads/scripts/rofi/dd_radio.json': No such file or directory
cp: cannot stat '/home/linuxcruizer/Downloads/scripts/rofi/themes/*.rasi': No such file or directory
cp: cannot stat '/home/linuxcruizer/Downloads/fonts/*': No such file or directory
cp: cannot stat '/home/linuxcruizer/Downloads/nemo/actions/*.nemo_action': No such file or directory
cp: cannot stat '/home/linuxcruizer/Downloads/nemo/scripts/*': No such file or directory
cp: cannot stat '/home/linuxcruizer/Downloads/*.desktop': No such file or directory
chmod: cannot access '/root/.local/share/dermodex/*.sh': No such file or directory
cp: cannot stat '/home/linuxcruizer/Downloads/scripts/watch_sounds.sh': No such file or directory
cp: cannot stat '/home/linuxcruizer/Downloads/scripts/watch_wallpaper.sh': No such file or directory
cp: cannot stat '/home/linuxcruizer/Downloads/scripts/cinnamon_dd.txt': No such file or directory
cp: cannot stat '/home/linuxcruizer/Downloads/scripts/config_update.py': No such file or directory
cp: cannot stat '/home/linuxcruizer/Downloads/scripts/*.ini': No such file or directory
cp: cannot stat '/home/linuxcruizer/Downloads/scripts/colors.py': No such file or directory
cp: cannot stat '/home/linuxcruizer/Downloads/scripts/gnome-terminal-profiles.dconf': No such file or directory
cp: cannot stat '/home/linuxcruizer/Downloads/scripts/gnome-terminal-profiles.dconf': No such file or directory
cp: cannot stat '/home/linuxcruizer/Downloads/wallpapers': No such file or directory
cp: cannot stat '/home/linuxcruizer/Downloads/src/icons': No such file or directory
cp: cannot stat '/home/linuxcruizer/Downloads/src/cinnamon/assets/dermodex': No such file or directory
cp: cannot stat '/home/linuxcruizer/Downloads/scripts/remix_assets.sh': No such file or directory
cp: cannot stat '/home/linuxcruizer/Downloads/deps/Fluent-gtk-theme/src/gtk/assets.txt': No such file or directory
cp: cannot stat '/home/linuxcruizer/Downloads/deps/Fluent-gtk-theme/src/gtk/assets.svg': No such file or directory
cp: cannot stat '/home/linuxcruizer/Downloads/deps/Fluent-gtk-theme/src/gtk/assets.svg': No such file or directory
cp: cannot stat '/home/linuxcruizer/Downloads/deps/Fluent-gtk-theme/src/gtk-2.0/assets-folder/assets.txt': No such file or directory
cp: cannot stat '/home/linuxcruizer/Downloads/deps/Fluent-gtk-theme/src/gtk-2.0/assets-folder/assets.svg': No such file or directory
cp: cannot stat '/home/linuxcruizer/Downloads/deps/Fluent-gtk-theme/src/gtk-2.0/assets-folder/assets.svg': No such file or directory
cp: cannot stat '/home/linuxcruizer/Downloads/src/index.theme': No such file or directory
cp: cannot stat '/home/linuxcruizer/Downloads/src/index.theme': No such file or directory
cp: cannot stat '/home/linuxcruizer/Downloads/src/cinnamon/thumbnail.png': No such file or directory
cp: cannot stat '/home/linuxcruizer/Downloads/src/cinnamon/thumbnail.png': No such file or directory
chmod: cannot access '/root/.local/share/dermodex/theme-ext/gtk/remix_assets.sh': No such file or directory
Downloading Sound Themes
/home/linuxcruizer/Downloads/DermoDeX-main/install.sh: line 307: cd: /home/linuxcruizer/Downloads/deps: No such file or directory
/home/linuxcruizer/Downloads/DermoDeX-main/install.sh: line 309: git: command not found
cp: cannot stat '/home/linuxcruizer/Downloads/deps/Cinnamon-PowerToys/sounds': No such file or directory
cp: cannot stat '/home/linuxcruizer/Downloads/sounds': No such file or directory
chmod: cannot access '/usr/share/sounds/scripts/set_sound_theme.sh': No such file or directory
cp: cannot stat '/home/linuxcruizer/Downloads/deps/Cinnamon-PowerToys/scripts/watch_trash.sh': No such file or directory
mv: failed to access '/root/.config/autostart/Power Toys - Trash Monitor.desktop': Not a directory
Downloading Color Icons
/home/linuxcruizer/Downloads/DermoDeX-main/install.sh: line 349: cd: /home/linuxcruizer/Downloads/deps: No such file or directory
/home/linuxcruizer/Downloads/DermoDeX-main/install.sh: line 350: git: command not found
/home/linuxcruizer/Downloads/DermoDeX-main/install.sh: line 351: cd: /home/linuxcruizer/Downloads/deps/Color-Icons: No such file or directory
tar (child): Color-Icons.tar.gz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
Downloading Royal Icons
/home/linuxcruizer/Downloads/DermoDeX-main/install.sh: line 356: cd: /home/linuxcruizer/Downloads/deps: No such file or directory
/home/linuxcruizer/Downloads/DermoDeX-main/install.sh: line 357: git: command not found
/home/linuxcruizer/Downloads/DermoDeX-main/install.sh: line 358: cd: /home/linuxcruizer/Downloads/deps/Royal-Z: No such file or directory
tar: Royal Z.tar.xz: Cannot open: No such file or directory
tar: Error is not recoverable: exiting now
cp: cannot stat '/home/linuxcruizer/Downloads/deps/Royal-Z/Royal Z/apps/scalable': No such file or directory
cp: cannot stat '/home/linuxcruizer/Downloads/deps/Color-Icons/Color-Icons/White-Icons': No such file or directory
cp: cannot stat '/home/linuxcruizer/Downloads/deps/Color-Icons/Color-Icons/Black-Icons': No such file or directory
cp: cannot stat '/home/linuxcruizer/Downloads/deps/Color-Icons/Color-Icons/Black-Icons/scalable/mimetypes/*': No such file or directory
cp: cannot stat '/home/linuxcruizer/Downloads/deps/Color-Icons/Color-Icons/Black-Icons/scalable/places/*.svg': No such file or directory
cp: cannot stat '/home/linuxcruizer/Downloads/deps/Color-Icons/Color-Icons/White-Icons/scalable/apps/*.svg': No such file or directory
cp: cannot stat '/home/linuxcruizer/Downloads/deps/Color-Icons/Color-Icons/White-Icons/scalable/categories/*.svg': No such file or directory
cp: cannot stat '/home/linuxcruizer/Downloads/deps/Color-Icons/Color-Icons/Black-Icons/scalable/places/*': No such file or directory
cp: cannot stat '/home/linuxcruizer/Downloads/deps/Color-Icons/Color-Icons/White-Icons': No such file or directory
cp: cannot stat '/home/linuxcruizer/Downloads/deps/Color-Icons/Color-Icons/Black-Icons': No such file or directory
cp: cannot stat '/root/.local/share/icons/White-Icons/scalable/mimetypes/*.svg': No such file or directory
cp: cannot stat '/home/linuxcruizer/Downloads/deps/Color-Icons/Color-Icons/White-Icons/scalable/apps/org.gnome.Terminal.svg': No such file or directory
cp: cannot stat '/home/linuxcruizer/Downloads/deps/Royal-Z/Royal Z/apps/scalable': No such file or directory
mv: cannot stat '/root/.local/share/dermodex/icons/breeze-dark_black/scalable': No such file or directory
cp: cannot stat '/home/linuxcruizer/Downloads/src/icons/breeze-dark_black/places': No such file or directory
cp: cannot stat '/home/linuxcruizer/Downloads/src/icons/trash/user-trash.svg': No such file or directory
cp: cannot stat '/home/linuxcruizer/Downloads/src/icons/trash/user-trash-full.svg': No such file or directory
cp: cannot stat '/home/linuxcruizer/Downloads/src/icons/trash/user-trash.svg': No such file or directory
cp: cannot stat '/home/linuxcruizer/Downloads/src/icons/trash/user-trash-full.svg': No such file or directory
Adjusting The Height Of The Panels
/home/linuxcruizer/Downloads/DermoDeX-main/install.sh: line 426: ./scripts/cinnamon_dd.txt: No such file or directory
Cinnamon is Ready to be reloaded by pressing CTRL+Alt+Esc!

[i] Cinnamon Version Cinnamon 5.6.7

[i] Install Complete

Run dd-wake to wake DermoDeX before changing the wallpaper.
Run dd-hold to keep your accent colors static when changing the wallpaper
Run dd-sleep to turn DermoDeX off for this session

Check the Startup Applications to toggle DermoDeX Monitor on/off at startup

Login screen can be 'blured' using the login_blur.png file in ~/.local/share/dermodex. To do this search for Login Window in the Control Panel.

cp: cannot stat '/home/linuxcruizer/Downloads/fonts/*': No such file or directory

[i] A directory in /usr/share/backgrounds needs to be writeable to allow for blured login backgrounds. A soft set of sounds from the linux-a11y sound theme project will also be dropped into the /usr/share/sounds directory. This too would need sudo to complete.

cp: cannot stat 'extension/dermodex-config@duracell80/files/*': No such file or directory
sed: can't read /root/.local/share/cinnamon/extensions/dermodex-config@duracell80/extension.js: No such file or directory
sed: can't read /root/.local/share/icons/DermoDeX/index.theme: No such file or directory
/home/linuxcruizer/Downloads/DermoDeX-main/install.sh: line 513: /usr/share/sounds/scripts/set_sound_theme.sh: No such file or directory
/home/linuxcruizer/Downloads/DermoDeX-main/install.sh: line 516: dd_refresh: command not found

**Comment by duracell80** [comment]
Hey thanks for dropping a note, this is like a research project and might help automate themes in the future. It would be great if there was a "Cinnamon DE Theme Builder", this stuff is very fascinating and so intricately layered.

Any help in debugging issues is very welcome. 

With an active internet connection (to download fluent theme and royal and color icons) try this in the terminal running each command once and pressing enter at the end of each line:

```
sudo apt install git
mkdir -p ~/git
cd ~/git
git clone https://github.com/duracell80/DermoDeX.git
cd ~/git/DermoDeX
chmod u+x *.sh
./install.sh
```
Wait at least 5 minutes for the script to install and run to completion and if all is well press Ctrl+C to stop the watcher script.

Then from your start menu search for extensions click on DermoDeX Configuration and press the small + icon bottom center of the extensions panel.

Logout and log back in may also help clear up some bumps after a theme build.

Right click the desktop for actions such as DermoDeX Refresh which should rebuild the theme.

**Comment by 13gemini** [comment]
Hi Lee,

Completed the instructions that you sent for the install and I am happy to
report that all is working well.  Thank you for your response, your much
appreciated assistance, and a wonderful theme engine that is making my
desktop, menus, and files (etc) look awesome!

Have a good one!

William

**Comment by duracell80** [comment]
Excellent good to hear William. Drop any suggestions / improvement ideas in and I'll take a look to see what I can see.

**Comment by 13gemini** [comment]
Hi Lee,

I have researched, but I cannot find how to activate dd_power or Super key
+ S as the screen comes up, but nothing happens after any of the buttons
(icons) are depressed. When reinstalling, I received to errors concerning
not being able to stat the json27 daemon and wallpaper watcher.  I placed
the wallpaper watcher in the startup, but received errors that it did not
startup when I accessed the log.   Thanks in advance.  Sorry for all the
questions.

Cinnamon 21.1 Linux Mint

William (gemini13)

**Comment by duracell80** [comment]
No problem at all, happy to help. The dd_ commands should have gone into the ~/.local/bin directory and may require a logout/login to catch. Closing the terminal and opening again should also re-read the bin directory. You can try pressing Alt+F2 and type in dd_ into the run box, pressing tab should show all those commands.

Rofi I recall being a little bit picky, not too sure how to debug the rofi menu not producing action, might be a file permissions issue with dd_power. Was that via mouse click? If so does using the keyboard to navigate menu and pressing enter work? I think also if Mint is doing an update it interferes with shutdown commands.

Try running ~/.local/bin/dd_power in terminal see if there are any messages relating to that script and check the permissions (chmod u+x ~/.local/bin/dd_power)

For changing / adding shortcuts try searching the start menu for Keyboard, go to the shortcuts tab and then custom shortcuts in the left sidebar. That's where you can add a custom command and then map the keys to it, so ~/.local/bin/dd_power as the command and Super + S as the binding.

https://www.technipages.com/linux-mint-how-to-create-new-custom-keyboard-shortcuts

The json file, I have a feeling might be a hangover from when I started this on Mint 20, and that file may not be needed now. The install might be looking for it and I just didn't remove that line.

Would you happen to have the startup log to paste here?

**Comment by duracell80** [comment]
I actually did just reproduce the rofi menu issue with the mouse click on icons, they require a double click. Using the keyboard worked. Double click LOL, why would they do that?

**Comment by 13gemini** [comment]
Startup Log, last startup 13:45

**Comment by 13gemini** [comment]
Hi Lee,
I can use the super key and Alt+F2 and type dd_power click on the icon I
want, and then hit enter, and it works fine.

William (gemini13)

**Comment by duracell80** [comment]
Got a solution for the json files. In the install.sh comment out
#cp $HOME/.cinnamon/configs/menu@cinnamon.org/0.json $HOME/.cinnamon/configs/menu@cinnamon.org/0.json.bak
#cp -f ./scripts/config_menu.json $HOME/.cinnamon/configs/menu@cinnamon.org/0.json
#cp $HOME/.cinnamon/configs/workspace-switcher@cinnamon.org/27.json $HOME/.cinnamon/configs/workspace-switcher@cinnamon.org/27.json.bak
#cp -f $CWD/scripts/config_workspace.json $HOME/.cinnamon/configs/workspace-switcher@cinnamon.org/27.json

And for the startup try adding
`cp -f $CWD/scripts/bin/dd_start.sh $HOME/.local/bin/dd_start`

In the section that's dealing with the dd_ files you can also copy that file in the terminal
`cp -f ~/git/DermoDeX/scripts/bin/dd_start.sh ~/.local/bin/dd_start`

And in the startup applications change the path to point at that file.

[Desktop Entry]
Type=Application
Exec=/home/yourusername/.local/bin/dd_start
X-GNOME-Autostart-enabled=false
NoDisplay=false
Hidden=false
Name[en_US]=DermoDex Wallpaper Watcher
Comment[en_US]=Watches for changes to wallpaper and then recalculates accent colors and rebuilds cinnamon.css
X-GNOME-Autostart-Delay=15

**Comment by 13gemini** [comment]
Hi Lee,

I completed the steps above, but unfortunately, in order for the power icon
to work requires a click and then enter.   Not really a big deal for me and
I am happy with the way it is.  Thanks for your assistance.  Very cool!

William (gemini13)

**Comment by 13gemini** [comment]
Lee,

I have attached screenshots of logs related to DermoDeX.  Hope they help.

William (gemini13)

---------- Forwarded message ---------
From: William Frantom ***@***.***>
Date: Mon, Jan 30, 2023 at 2:12 PM
Subject: Re: [duracell80/DermoDeX] Unable to complete install and setup of
DermoDex (Issue #1)
To: duracell80/DermoDeX <
***@***.***>


Hi Lee,

I completed the steps above, but unfortunately, in order for the power icon
to work requires a click and then enter.   Not really a big deal for me and
I am happy with the way it is.  Thanks for your assistance.  Very cool!

William (gemini13)

**Comment by duracell80** [comment]
Thanks for the encouragement. I might be unaware how to see the pictures in GitHub but I'm not seeing the logs.

I did some more tweaks over the weekend to the install to iron out these bumps, to get those go to the root git directory and do a git fetch / git pull

$ cd ~/git/DermoDeX
$ git fetch
$ git pull

**Comment by 13gemini** [comment]
Hi Lee,

Thanks for all the help :)  I completed the updates as prescribed above,
everything working fine.

William (gemini13)

**Comment by 13gemini** [comment]
Hi Lee,

In working with DermoDeX for the last few days, I came across an anomaly
that I think you may find interesting.  When installing with GNOME
Terminal, everything works well.  However, when installing DermoDeX with a
QTerminal, I receive errors unable to stat due to files not being found.

So I started over with just the GNOME Terminal and everything appears to be
working properly now.  I am not sure why the difference, but I thought I
would report it to you.

Thanks for such a great theme engine and the the tremendous amount of work
that you are putting into it.

William (gemini13)
